# Generated by Django 3.1.7 on 2023-02-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='asd', upload_to='pic'),
            preserve_default=False,
        ),
    ]
